name: Prisma Cloud Checkov Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  checkov-scan:
    name: Run Checkov with Prisma Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Pull Docker image
        run: docker pull abdo01145/shopping:latest

      - name: Prisma Cloud image scan
        id: scan
        uses: PaloAltoNetworks/prisma-cloud-scan@v1.5
        with:
          pcc_console_url: "https://65.108.208.146:32159"
          pcc_user: "admin"
          pcc_pass: "AdminP@$$w0rd"
          image_name: abdo01145/shopping:latest

