name: Prisma Cloud Checkov Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read  # ✅ Most workflows only need read access to the repo code

jobs:
  checkov-scan:
    name: Run Checkov with Prisma Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Prisma Cloud image scan
        id: scan
        uses: PaloAltoNetworks/prisma-cloud-scan@v1.5
        with:
          pcc_console_url: "https://us-east1.cloud.twistlock.com/us-2-158320372"
          pcc_user: "bbafb6da-de3d-4f92-8590-cba5ed71efc3"
          pcc_pass: "gMrXg7Tmy2KAaciGygayepvpH20="
          image_name: abdo01145/shopping:latest

      # (Optional) for compatibility with GitHub's code scanning alerts
      - name: Upload SARIF file
        if: ${{ always() }} # necessary if using failure thresholds in the image scan
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif_file }}

